#ifndef HSG_EVENTTYPE_H_
#define HSG_EVENTTYPE_H_

enum EventType{
    SYSTEM_EXIT = 1,

    SYSTEM_VIDEO_INIT = 2,
    SYSTEM_VIDEO_UPDATE = 3,

    SYSTEM_KEY_LEFT_DOWN = 4,
    SYSTEM_KEY_RIGHT_DOWN = 5,
    SYSTEM_KEY_LEFT_UP = 6,
    SYSTEM_KEY_RIGHT_UP = 7,
    SYSTEM_KEY_SPC = 8,

    SYSTEM_MOUSE_CLICK = 9,

    GAME_BRICK_CRASH = 10,
    GAME_WIN = 11,
    GAME_START = 12
};


#endif /* HSG_EVENTTYPE_H_ */
